apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:UvA+z13b0cVh9lJ7QMiGmdda5nkcZIaJG0JFsUUCTERR+MlWOn3vJJ23wyhG/F1XB6wISJXgDBPUciQWkvUloFbbvtPnFjFP19Fddg1um4/6VyFoI9zR+MuMbBvZ+7krA7I0O3Dma3Kj8xXW52qczEruWweu3EAQSDy8KxpnQfUktVtIz7yPc9g8JpF30Jfzd+CwA1NmhDAbuTzcUAnVMlkEcjrRO1U+RYiLujVgQyhYSzxM1FJj7YBRKe6tr8oVsoAQRf4WtCE6CjkS+ybrIvuI/faecocJ5DXMdszja47zcSPsnjLE/tQ3WJgiEQGh6y2MoUFcZerZfTQ1aBpb8Hw/roNDAhAgnDmnnZBgYETaOvjz1X44reBZ9BjRWDCB,iv:pXm/q7OYvdmto+6WRuWU1Hi13pacrvcgGbSB5rm6qS0=,tag:B2VPgh7t7kLeJbt6zk6ilw==,type:str]
    identity.pub: ENC[AES256_GCM,data:0rRNCZjAQ18YeW5RUNNW9O74r9PapavdSBCicszpqkZPMpIlhmAzSQib0aI4NZpnrNsd+kF+6pjnAxxSyR0pb2XbRXMcl7dkbibmtbcllsap50KS6tmMWyy1gjTBz6BhYrJvY6scJ3Q6nDlcrEgkIIeCBL+Kyhww/tp8axIbIoX8TfBrsDbmJPjAIWoBbV0u7QQtwkwbux6vSi0sF6pCZF1GeCTucjiXpH5wPCP0ugy/uw/Kk53y3xkQ35q2MbrYnsYnIw2tTVPrVELr9w==,iv:VIsR5cMX2Mo6kUvjn+vmfGmQeCdfc1WeXM1AsMQuo70=,tag:m9F7T49e3i3PWggmTZ0wXg==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZrMZKz9VnbZ4h8LRMPU3AEaVD/ebQFeZI/kZMVLcX9uc0EmaMCmypYiunSuOyFatdC4Sjy2lj420JZjl+mZodqinAWuNCiWzaUqtuiQBPrYr3cXYh315kDfYt4YvgC4+mPHaHABDrLysptHFNlXdzLB8CeWrTrPdlg1crPh7NiVKYvnyzBdMx3x1nTYVZg9zXg20H2ZxYpI96lTNxndlvXchkhNutKikaeIE,iv:QZ/JZqO7Piam6UeW4fAQjgOCfH9iODfxMEUxNU9C7f4=,tag:kAdte/QwZubEbRE+6c3EoA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1nvyuzu5f6y5q6navmgp3xfjgtdyknqa9skle4kc40mdmngrvpfpszpvekr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTXhoZ01kaWNldW5nY1pj
            Q1pZL3VSbGRWQ0dOOXQ3MjdVQ2Evb0xlK0NNClhQS2lBc3B1TlovUnZiTmdWS3Bi
            YzZuemlXZjVDelBJbndvRWVBS1JrSnMKLS0tIE5hS3VucXk4bk5PaGJNMC9ZUkJO
            ZmN1MFBJQXZ3LzJUdU9aWlQ3RGZlVm8Kx28kqEJrR5gCgVhTpVZ+Nw6oKCYWt14q
            FhWnZsbIWXDyep43qLazmG3G22L7WPxHDLqG5vyDQqAwsgp2Zx2uDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T21:35:25Z"
    mac: ENC[AES256_GCM,data:MIijGk5WZw/L1S+vxyB66dzEh9W+bVP6U2D+N9br4qOv9fIc02YVLDolgze2Gmubt98wbPs9reVdWWALXCtlsmHPDu8h1oKt2BWSC1SKW/K++XRFID86f2g7zfSmOPUR8e4FlTdmhD6ANM/yWIBm9S7sRfN/OA2VHUveLzFSoK4=,iv:UycHkzxdlgeQxdM8ao+gXk9Q299nYaM7ATzftepVPeI=,tag:SAZeifGWHjP7guz8VRRZmA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
