apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hBfoEHnmsGFV88ffNfHsz5RnbF94bo1bb0DnIH3/AAP3btQnlgfrg6jp1WUHLasaMwCgNQ8MP0IgxXCC5p6VJ1DhYsjGZIuAk98kw+zEUbYiIKqgv4xsrDdiZ19kh3o+gbljlYwYHi9qvKuqoqgL9vR5xdzXeg98ZJzYCqdFU98sq6qa5UAsnWAuMRvjnONp15gcgqVZecBetDuubdQzxF+8t/YsC50u7lHMRbMJRz5EBIuLiwZIiWVS8t6KZEARHQIHqy0i3yNWhajLKATDNIJpLxkhMle2b9a5Dag6rlQADyZvffa7IIfCBaDr773JpihGva6LCh9Z4HEaJqT59RMtvl75R34eBEaQA5Ikfe1AdIrnO02+QPjRSmuTatw1,iv:UtngzmC3lT056xvGOU6UK4w0fgE6Ge5eA1KRrgJXy9s=,tag:xItUqT4VbYwAwhFdHML/fA==,type:str]
    identity.pub: ENC[AES256_GCM,data:0+8ckbHgg2jlEivx+rw1+hWimbFeLRjJ4+mfRrPkAgsbk4Fbw6NTjEgbhGO6hSgyehDrqTt0sa8oCmN4Z+XTyrn0msfAQcAleOaQpm6dPrs2qymnut2xQVsn3w39pCetPLbQCWj3GuOkYeOqDFzL1cNP1pgrxXldwlzrLZEFWQp7ka47qOh4xsPeai7w+LqXaDn6mnaWc72UeKdvSjgPGTpXd3bQ7yhJK/epeNd1jSR8WifNWW/DlnqpPEgzGDA3sjFuipSWf3sStFvwJQ==,iv:15mBsp2y6UORB/d+nbVKgYd8HV1FECSeAK6/jR2+N3E=,tag:m08lujiloxu39BmnEbHG2A==,type:str]
    known_hosts: ENC[AES256_GCM,data:rBm/GpdB42x7MWCQOdK3ZnrZElLoyNw/6QS97KTYHntCDu8ozVa47N9ijM4cR1OSsr0yiqwT+PPpYoMZwnaZDMDFkKLmQYWDu0zffCW7jCsf2yyzK3qYPS5o5GB6kpbMhi4cxwc3MIOheGl03LRRWNYrQPIXKZQZdvr0kihlS4Ib6HhG/4h493FBsEtvIKGTstrIke4FtKsYcli7BCXhmPkO++55eFat74Sd,iv:2TXb+kHTN5iyx/i1Mv6rptdcUzt4hfU99RQMS5xD674=,tag:BEnaApkaXILYIrpouyxdUw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1nvyuzu5f6y5q6navmgp3xfjgtdyknqa9skle4kc40mdmngrvpfpszpvekr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dnBnYkx4YWhtQnY3Mkt5
            NVZrRmZKbUpxTThMdFFoYUwyN1ByWXN2QkJFCjd0RnQ4aUtXeUdJOWZGTGM3bGo5
            RFkxdDlTeGhhMjJFdGU2MTIxencwT0EKLS0tIGRoTnRjVVVxejdIRWl2V2ZENVVJ
            VVhUTnZUVHlLRTVmU2xLejNtaitkUFEKAHfBfyXblFvs0gj5FMYcVB+FmlZ+xRsC
            1Zl/MS+2OapEMrmZ+2nhrQH9wL76QvO9gqIkLtSAvn3Xq3txBv8Ypg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T22:19:11Z"
    mac: ENC[AES256_GCM,data:wfgQOBbBhI8FS6ziurvoVO7pbMxXjCb8k2kxUlxpDF5u/TV+VzW8wzg8j9asSMbfUP4VkFd2DrhSTyGzP/aJ31I9nbRN0Ml8qtNtD0fmFOVpXmNNle/GC297nP9oKbtmAPwYzYjfb8TTT3kDgqHuz3U8do+x8TSRu6PbJ4v8bX0=,iv:myxglnEp6aa+ehH0Zd8MzJAASp8P6P5eezr5iFyMBs0=,tag:XXyqUoRwWbcJLJXGU2PAXw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
