apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:bMCfwyDZn88qrYRO2xul5sl0IjaulmJ5WcHfAjrucMS/9R269H/gYUqIZBcjdEkfe7Cn0KndfrZEZcAP3hjg61tabOCYokyc3pVvFdFWPPfYoMYhDpIf/kwFkUsitmHVhfr2L72FN8W/mEntRSobGvZon8tyUoPUwL+Ncrw6UQyFCDWNSJMJcLFI0IOUaXKHtp06Ttrh2jOmMBc13aySewEzK3ZYc/+YGJDgExXfSbUJ7z2veLVe3BlvQ8AA+RH08GkpmS9MxqlIjz3DwFp4+QKDqihJpCIrZG6Nq0yIysZKXzHWW/+H4eeor0ZDuplWYUq8K6ZwodivGrUHcsf4Sj6qPl5rjGtqcN3Z26fz8cFiSHZ2CM1f2RVFSMY51hAu,iv:+z4XjhUQRHRJ3oHGotXqKvAlkYjsYEqOe+83cUMICqk=,tag:+pwJFY9rGNkakPy0JSKQNQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:bndV/Drtz5jEEGu9aAeL8YDe5gPdxNHCp89Gq1JNny+BL5CffZhOhtUEQcyPx6FbV3aYu6FkMMDSB7X8Q6+9pO3rvluvwl1jjid236Sl83PobPLQtzArJMO6vDJ09RnezFQ0aRwVb67dmEOgc5WYEW/TObBn/ODp4Lh9Iw8jeVj6BXAvnHmcyJpq0IokKKOxUEFrlymSAcow3iwHlEQo2I6GOVFhmO7qhm4fptLFPQ3gidwgAB9JpVruJXs2zthb6OXw1oVViYK8TStxcA==,iv:P78UbTZO5EDtq7qG1oG9F6zOrxbKJnEaMeh8QHGsfc4=,tag:nPTb11piLPrpu/7Z8E06ZA==,type:str]
    known_hosts: ENC[AES256_GCM,data:dvMQvJj0FxUz6r/JvissrnnJ49aQXOsu0S9sg0fqFQsmBnsWXjTPoJa+fTvbUw1B8ywPyOl7HHfGF0YmvMhisbA3twAvUKomTF6tR2onKQLYvo9+nHhWLlzdS3c5xDajwKpzrc0Rz3jk9ydlGbHpYz7R8w6EnujpeDezIBIvWjmOI3M2jrOuq9015mw4LPIuv/XPzXy+D9NOPy7jqACBx/Ui+DrPkfuYxCdd,iv:L0z3zZlrJJBGKA5agwleamHerrilpYIjP8Z1BWj1Jek=,tag:V8rZl+uMPpxkshJRN18mAQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1nvyuzu5f6y5q6navmgp3xfjgtdyknqa9skle4kc40mdmngrvpfpszpvekr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuckxTRWpNNW5KZndrQjVN
            OTJROGs1WFJxaGt5MmNjdmlPb1FuSmRYOVYwCjNFK1QybWcyVlV3TzBCamplKzJr
            VFVZRlc3SXVab2IyM1BWMVdKOVNNUXMKLS0tIDlCVnVzSGVlWHIwb3V0NDBOOE5T
            RTZZTlZPV2t3M1J4K1VRU0ZHVVF4ZDAKHQXSscptvUytvXZoa3IwUKT+vuH7D7z8
            LHTJ9JMU4CSHE3Krx09wP8iboNExVJgiE7A13sU/P6QAympzzUHRDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T19:18:44Z"
    mac: ENC[AES256_GCM,data:HHl3XNIu/ZqK2S5IJvp6PbOJa7Qpv/e9EHfzoyqTEWehiiFxKpH6cc6Rjn5JV1XE9PgP6bfblCAmz4Ovvvi3zA08I2fWWEUYwri2ARrqAwU8IBiwJ3As24TCNb5cIZHAro+7jZxsLntUMqNsIj1oBTIIsMCODemQUMrtW3wYQfg=,iv:4etcmUvsXFjE1punVbaeMUBEo9HASXxKZuXhMUqsDuQ=,tag:gWACs6zah1i1UIuCihDcSg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
