apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:iSrPWsP/GlN6RQ7Z4t3wu7+goNZVz5Qk2vKu0Jll2UIU/xJhqmu4yrRus9RrfhCZBCVhQNVcQrrs4bzmNWHwP9++mw4VOhLLUJMnjDwjrLBWMF4Rt9nFSH2iT+KrwQyqWGbVOrxwYzmxQRTR2TLtgcjJiav2wY4kikhnksFPRITgqEuVs51aVgZ/BUb6P2XpbDbNnx84YGygn9G9s8w4QgsiGcB8kX/JILbY7HfmCp/8QlSYdHEx2OCQlQcAO4OZn66sL8k2/ZFTCS7U9F18zFt5Sw25vcX6xJZMHevuTq+btmgEyVfVcO2EFpUVVhKIr2lDNAAiD98ZNWU94O4lZmDi0Vn+doRH53FinSnbV9HY0DxArvPf4LrOMK6Y4htb,iv:MyGoFR6urPMbb+kuV0I+9AUBghfEDL47+OQr6uHbU7w=,tag:ggcvHtONsmDETmldkQHGIw==,type:str]
    identity.pub: ENC[AES256_GCM,data:5gE3CxOCSYcb2yu3oUIHbJ15t6Q6bdttzIEdurKeNu3gE76Ee6DtHSvz1s9K9z3Giss78KYhYA1euwmxckYzimlvbgQ1c0TL66mlQawJZqEhctabrPq48E2xjLt+ADWd6MonQZuucgcK2bcKukXzdyevlIU0XQOKMhsJoJTM4Nr9t++hdvxxeXmDJ1tFXDxmcdZUTkfTffcu0e7c4ATbWD0bWQdw8IdwPtiD69Nu5uZ3nHK0506QbHuVSdsK8Zy1fJlHIEhB8swxDt2Lvw==,iv:QQ5pJttvNeVz0q9j8qQDq/heQnOMCrQ1WDdCYixocqI=,tag:Zt4Vd94sBjNjgbIczsCmcw==,type:str]
    known_hosts: ENC[AES256_GCM,data:STZKED8k7tHb2SR1pJwf7LvgBO/ZX0YOEGI7bHkyqtRD00HrUo9cE96+Ylq5WJnnUfOfaVjP00yCsnPGg3KpSl7qln01QwokgJZtqEae3oWqDzs9xwHBRTaosV+LikieXIu/xDF04CKtk32kILTBvndf380drRHYgLNZLU1hjJNFxlFSkoFnCbCL5kMtFXwOftbB9HWVlxeVPBvTSg1Od/XNNhdFwJcmFSJl,iv:zHJLyTH70/WSSBQmDcZo/Qs5DSsBJjcQ2e40kYKn+Rk=,tag:noDc+TvTvgnR+YHoQvkP5w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1nvyuzu5f6y5q6navmgp3xfjgtdyknqa9skle4kc40mdmngrvpfpszpvekr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMS05uNVI2cmJTUmdyWC9z
            aXF3bXlVcmY3enNVWTZuZ3lFMEl3eTRMRkd3CjNGUE12UHpGYStVN0tXMlhlMEIv
            aE50UFNyRmIyYVdpcFRjQ1dVUzBZM1UKLS0tIGJaa0paaTFOdENsM1oveUZWQnhq
            UDRLc2pHWStNMHFOTjQzc1ZsVnJyN00KmzW8xSSqBp9OcGh8bjyvPl4OTkN+BK6x
            Rwy+LEj0EJnokwm8uN9JO6NEBtKTmwBn9i0ghbXN4r2HwVf7zJZGHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T18:14:52Z"
    mac: ENC[AES256_GCM,data:ab6BbKIDSF75lTZeNoArN5O2hjPx6BLuB71n6MohdXx9bchSWZKzBncPCxKQjvAO1St/h+JJLysE9+WlNZ4gm3MfJY+5mbNslUOwc+m10yqkP2d0nzEiFRuOBFSognu0riuJsfOXpoa8LXRxR0ykeDZpfYvX2YnSLShqrVyVrIw=,iv:NzDzlcc4BjRc8YkDnYFpSaXsJlIPCQmoEBLrM9BW4Dw=,tag:JYpmVvN7mQwL/k4OgQ0w9g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
