apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:fFQluP29GOcuV9vAX0wiof9CM1UISMbkq7i9ZUtdp6vD8H1sWVgRR67IEiGPb+yxipCBTlxkTbcR+CCYC2GonoDJS8Q1eYhNYLBtqf06tWfBtznV/6raHN8HoXbBEyTQTrZqDYcgIeIPx7xpm1OJ0ASqqPHfgEY3cZJAa3uW99oTT7fFUFUyS/EKOHdaB5QLKwhjuSuXa+NDkbeJq4BKWW/FHg+xuEUHBEcrJ/7bWLvExqOXWYPcD2RadKUVXplnXDXqZOXhUPFX2x4v2VfP0X7lxHVRXx/NMs2ztk9QlOh6dzYag9FNkwCyG9rGlbQnVkl/JMRTeAOd7Na+qerHTpXkTuT07PfvLoVp1Q4s/W71lMD1w4ScNGFfI6gv2jeU,iv:7kuUjn6OPO1Nzq2hBGoQ74o6HOEuF/pHbvOcESC893g=,tag:65xOOrerrAVHNKLRmrPBvA==,type:str]
    identity.pub: ENC[AES256_GCM,data:oPIl2jwvfRz9BhqN8pVoFxS3Glw2PRcOb4wmSXO623BqW5xoxPSas925eCvEBbV3pK1G7zHBb3L9f2OfpZzqPQo48rWhK2252nnzipcOY5XPoRoutXWfBtJkpE3IyJAlWXMQL1BJgz21RoHPd1fDpp+xiYxMROsM6b/H9hWOXc1WR8KWCfyk5+51+f3/VlFhjf7u7iU+t6C364nnsKdcSAm3X94aMQxjyNjRA2+mtK0Y/tIb6OxwxE3vopPeKvDJzfD/pnh6KvGOgGGfyQ==,iv:2+ySngQSyzYrYfDW2lNkQ1A+W6nnQwkHz5o+Ti5Ehd8=,tag:lwDmPyRIY3dDGtFcWd2wog==,type:str]
    known_hosts: ENC[AES256_GCM,data:hRfGGE3+q2fabSYkcPpTYmHDZ4Wnc5AjMcLSsHcD4C5/eRFD09R7hPTAEkJ3qW1GBdMModxhDO0t/IYnYi46ulHl5E9ylTP8iuCzBR8ffRqYXkjrTFZUVWdeYALukWB0sa6pEVp3ZSRYxcPbXh0UbHNWmXylAhti2bzA3XOXa8cSo/8LZxAtkcR9cXbcDrs8ad+Stzvn6haFe4XGn+dSGY3t5jKiA2oXQxZU,iv:peZl1wNYmqbEq8XBcUoOhvgkFi872dzneujLLt5yWBk=,tag:2RV5cnCgN1Defk0K8WW2ug==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1nvyuzu5f6y5q6navmgp3xfjgtdyknqa9skle4kc40mdmngrvpfpszpvekr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRE9QSEpYQWRhMXR6YlNy
            WVZBbHhEa3NlN0pxUWx4RmcrZGU2Zjlpam1zCkdtQ1pIcnNObDZvcjFreFBWWWNl
            K2ErMXU1bDBaUUUxZmRtcmxYMm0zYjAKLS0tIFlnMVFBOUxURFdzNVFxUVhCN2N5
            Szc5U1ROTWNiMEYxS1ZIRWJ3c2RPL2MK3yEGCpytH5Rv5IYvNY7kWSIEdzfu558q
            wH2SLHtMfso0Ksxtmlr1IooZfyTM1Et4KgpUy12V/HI/XGBdyQxhYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T21:01:24Z"
    mac: ENC[AES256_GCM,data:ABHDI99UEcwgPZozPh8DLZBFdZapc62w8PESLH/O9ecuS9Ulc1FF7GCranMEKEBenMoJi6yQc+WrQPyEKApU3ZWwdSILutKYTHawVEc5Vqt7EF7/xIyNK60x95c10Vf4VCRqRCGX8Y0Qeg6Ou453Hu2v/m1AdrKiPCBfSqVoKds=,iv:OcCkrCJ+2Vb/HWzhKNMDb0G8RnPo75J2DPnDzQ7ax4U=,tag:HKE08Gvqv21jfyYzNqWI3A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
