apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:qYKUT+KHxEDfM/B1/x1aLY+PUVO5XpK+JYgts0btAOBQxlJ/yd+5/FwbW6pcCLI6o32hbXhYjTOFhQbfokw7LD9xb/2VAFxOw6k+hdw+OvDuIrN3UzgSf/6oFKllatdGUx7/kuiKGx6yoSzFcCHl09Rw1iUzWDhOSFIRbugKn/qwyMbS53hGpGgnecB1joqR9a3zFJT4xAA63D1fmwBTpOhDfnL0Xd9Bc/HXPXHF2AcgKUtVdNKXcPD+660/kTea+I37VxCMdeVS7Q8etwe4qmn5Mcw17C/wvciQq8myYTH2Pzl7dwml44YlQESigWjlbhwoP2WKrT4heWdNUm3dJLSCxvMJWXU4R446AYVrxZ7frtXZjeyeEwKX9nBKLWss,iv:9wydsMonUPVQLdBpKTdiV51F8fc2do0B31rzi9kyFIA=,tag:Yov6tjJ1Bj19syZqHGLbJA==,type:str]
    identity.pub: ENC[AES256_GCM,data:CgTf2yJhB0pHVXBXenCiUZ6ue8EK4gmVn2WepPXoqMe4S8vhAc9X63BKI0DXyMgP/4kZiQ5rsQCF4euQ1pvWuU31xRmDWvjDY8p1xoiOLa6oG2lfLQDMRsuo37/xBWNwRKI9Q8zwcKteR0+ydhC+Z7afvKcnasUYSrvzwy1PHAfMU+cUoD5oTjmbWB2HUvUpf3zxRk6pHtheG+JFi4C8C2rB4ug+K1vW7EOcLVX4GSGIEjAKlT4DHGC2X/VRcto4xhTAQOQJD0CzPzekCw==,iv:xvK8lRd5WBnNjvvxv5p245YZyTqIjPqyE0t/qniRASk=,tag:bvqGmAhsUGOVWMABLfZU+w==,type:str]
    known_hosts: ENC[AES256_GCM,data:YG6ZPGbW4ualQMD8Glv0yLdZgufgVE2fv022w2zqx480hovvtfZ3IncaB9a24Pt+S5mhT92h7UZk0Oz/rFjtMtQTsR2lSy2mvFFXnLbnBqUzBhl/Rt5sXASXUz/9RQexPYz0luW6P+TA1JQOb8KmttAvkQOLSyrYIghLrkIw+jYEYaQdSIQkKQ7PHOHZ4roaF9Es3lVG/u8yBRV6GJni8t8/geD+iN1Wwujw,iv:Q/rW2z/AqKJ2iB0w5NpoOIDdcbYQhAZct1hVrlkvXNc=,tag:83fNtoFFTptAZZ1Zhc53gA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1nvyuzu5f6y5q6navmgp3xfjgtdyknqa9skle4kc40mdmngrvpfpszpvekr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNWc0M1lJSEh1YUFCZFp4
            UFNZQktaRGZHNE9MYzdRaUVjd0VkQUdBdFZJCnlmSHZZTm1CNGNrQnhQSTdzVG45
            bEtMRXF2UmVneEJNWjZKUGM5c1A1WjQKLS0tIFpkc2VRV2dIMkZJQnBQL0RtTFk2
            eWVSeGtMMUhmeWZEdjZtVFlzanVpUlEKJDJ/Ab/0bZgNAHdhuVtcTSPHG4fbEdPm
            nyfX22NnOVK7qTXDxwHL7QtOpeOiJwZfw3dLJrzAXQPi8aWGlFMVTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T22:56:24Z"
    mac: ENC[AES256_GCM,data:qrA4f5+1sxt4GsU35c6oBGBU/0akY3YevMAaJY9SUqGbUEUjXyx9CnJRtfW7PnEVg4sWfFd3M5VjZ3in7Q4YNeG0r54sgXvC9/DGZAhmoViQnyM/LnJJ7DZw8JG5dh/1QmGRpdTWku6JMKKWhutZvqjitgvhA0SlwkdadTVqnLk=,iv:iRt3i4WsfaXpRryEOAI3RUihA5K2YfycWQMV2lBEWkk=,tag:RroQ3I5E1UkE1idPDtrKSg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
