apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:aZI1hbz/bV5R4Qpt1Pk+bwzVYltbaIpy2dqCkPlgSUurkGHS9IZyj6Dge+NSpTNz/I/Y9sD+TaFMKOLoyFM3M9RsG8FAyxOE+VDRuuELFQqr4VeIrXfUaj+IW6Vuk4S06otKw5g7oBYVmiApySbyx/XML7hxDIee/blrWX3TXNlKD1CnQGfMwAWmowdzdXtCTNTIX8/KsSxs9yVsOGkfh8AL43h+Z5pfctRv0I+DONcAZA7CzeoR79mYTnHGx0NyzKlT3UaZyDYUyb64Hme9Iy72DXHsjzjK9/ogDqJUSgtYy8uL88qzygYc9g2yS/o2XiFGOegGvM6VCkkONp9bsvFKT5UhPHE29gTptnw367O8yuCKVtPiXivNhOo7/CkG,iv:FrLec0mwU5Tr/ZifeHJ4d6yl19ks38pqDxyGa1BQMUw=,tag:94+YIo9yiX+guQroqxyPKg==,type:str]
    identity.pub: ENC[AES256_GCM,data:IspaBZRsuaFibTVxCG6D2Ythy+UZxWb+bh6e709wG6g7ULTpZYtZEtKNYkPsWzWw8B2xDJMCxOK9VQAX98YLvW0dVi4I018bMJgAC/p54sspIsjtbG1cwAO6F3DTIa5cnf98Ls0degsM5iIKzmbmXKwaIyBplUXwgQz3A+U3QdSFeMLoLAmC0rgr9bIaxvCQ8d/ocqgfYArhqkp0C+llwV9raCGS3aSHFHAR+nJheX9J5H9rJvjA/S3tzfkDI2y4rg+rdtxxz7X2tvCBUA==,iv:rCUlgTR+dg7dzSifvt0SG5L9aWkJAxBJhbNeF/mpqfE=,tag:/neMRdcLLjFKy7GlfowrLQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:YcsWCAfxUydvxu1lfEu6YumJgUmFqii3gQ78YMEHDr9Z9OBt4hudTyRpyJZAylySleBlUX3QQiIsTaucnW0sVidZrnGBtr96kS/jRcVTDady1TKAzm5GiDyNT8tzFvn9q2+kLuu5lEUkd20lxLDzZo0/afkOdJmA1Jbqj9oy5u3xcvLU+VcG8YhejwnjJywlPIe26MQWu+yXVwJAg5Dl/EcG5g/EybmeTKkR,iv:1RV8KgJHBGtA+qHbrMHSgYl9PwROna5RzhM6zmQjimU=,tag:8U/6AAgkahVZOnpP6m4vgw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1nvyuzu5f6y5q6navmgp3xfjgtdyknqa9skle4kc40mdmngrvpfpszpvekr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWnhlTm9KWlB5RzI3MFo1
            cHFoRUkxVjlZQUNYWUdzcXovZG5EVW1ZQzJjCnI5eEJtQ21VWnJFL1JydkxnMzJF
            WTFYTVRvSXdXSFd0THcwWFgwalY2MncKLS0tIHorOENGK2FyeXpjcEsxUnV5aUdX
            QnBjcWtPUVk4L21ISTAxTWEzZDJvSlEKY6sjn2IkLan+NfLr+Cj37Ul2GJEQHyPi
            TNEa7qUYN4j4aFGSR5KuZSUcm5It2Wi4M2YHqFdVniYYIou30C6sJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T04:33:26Z"
    mac: ENC[AES256_GCM,data:zC9d2IUghWVMw7v1kI2t+18Aiv//BJ8iXX36y7TvuJpE5RHoQ0cP2hck3O1tHtEaxeuO5gEz5h9aIihD5QQOm5Dm18ioLg6tVf1PGUWvCzXwzepCdPrULFlq/N3Fbnq/adw5+EHtKalSmXhkrhVeK+gYJTVO5vy+xZ8gABMS84s=,iv:VNXkbexOGtawMED654mzqBW7t0b81fm+UCNF3kcKY1Y=,tag:QkvQY4FOLjPOOs/NwlcaVg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
