apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tNlyNx6bGKLmaJQdgxDK+F5ITxsTd8r19UA7iK1+7/292i1nBCmWp403hnu0QerMV4sH78E3tHuATQ5X0hIVnBGM2sTvGhQulPNece8+Y+JMxUYVHwG5c2DFjAGSVY4ZwLYg9gqiAjt6yKxImZJjBd2Ij92XxDjfPJu/qAoxDWqTScSbjR1xPwdO1SbnPMz2wiLVs3Ykt11s1MG3f5o8Y4Imti5JDhvcP9Siu/xrvFMi0vRBFHjbNtpPknT2mhqWq2Yb0fMB8aQmIWNLI+RgSr4p0s+/XmdxjUAKjh+ME+iVK+GNKBse7WPVtVoYx2aaDP1KJ2EgukaWKAXwzwjmtOQWoddSJB422j89uybI9ZXcTr6BAEzeEn9LYFkQq1Gc,iv:v7HrRIuzV70x6947g+Io4WvyVtr3Fy1uixchGHJ33gQ=,tag:oA7ETwuI+13VhG8lgyPQWw==,type:str]
    identity.pub: ENC[AES256_GCM,data:TN4c/Na7n3BfnAxO5biiyvpmj/3gyXcts6zFsQ2j6lPi0TZLRvVdPUPaSIHyduDbP7BUSuTAD6/Y781MXldsUQdD1ehD4Ch6AgudvlSYpMM8QSvI5HHhR93cr4XtZfjCbVn2TBHaer5akNJZXHrOfpwrX0pKTjtw1vdi3nb2qzXWLHn3KqUDLNpiUIessqWG9xGD6u2ozfRduxmxRsNPCinQHCOdpzAjHbppEUKa64Su8QQXOeqYp6qb/hlODy8ZFF4kQO11tn/dSPhgcA==,iv:fEWX/ESwoDJmvE/GKhJJvWOhZ5bkpN5HaWiqUhe2D5M=,tag:vXzzEGbiOUOxAaMoX0y1hg==,type:str]
    known_hosts: ENC[AES256_GCM,data:C6v8916i2eF417YY2vQxqxMsd6ICBNW5H9fgJcxPFsR08Pae06mDO5vqDJY3mFDJ69L8pRd9IASc3f6pMWrRBQPZiMqrqm0c3evZLa4gJ7aqBuGERuHTSA3vuVqZaaZu7iHHVts1hFdO6A4sc1Z6qVSBBXQnCPuO8zXlfX0ZC42+w+RiUDdCxWXRvqmJnpTfAk3pw2NsghtwKewMa7S868a5h8NACGl7D+rH,iv:jPg1/BcP/xQnsWuh6MiryU2c6S1yIXYTH9nV4UgjHUE=,tag:BSkgOCuntJVmBhI4hWCdag==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1nvyuzu5f6y5q6navmgp3xfjgtdyknqa9skle4kc40mdmngrvpfpszpvekr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVd1g4akRwUVdGT3I3UDF6
            OGFtQTBHbWF3WjJyY3JiZEZCWlN0V09sYkRrCmhtTmQzdkF6enQ2ZWxLb096QWx6
            OVF6RkJTVHIwY2t5MC96Sk9MRWJ4b2sKLS0tIFoxZzRRa3Y2VmRuSklKaXFKcm1l
            OXFvaEFIVGxteEphTTBvZEpJQWZwRFkKu2VxlYUI0nc6n7bzQRQsirSJnSqA5rOb
            HtKQEcCJrwIT8Co9gz86iXrUR0Ri2bdwLH5eDA0gpLotRZJq5nm51Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T20:12:18Z"
    mac: ENC[AES256_GCM,data:Aoh/48KovJKkDcJ3eFRvtvXwwJlKL8cQ/IgiQiBSPs87ctYqnYUDjf2u2L+15QgH7YIaNqT5028tHrzofsMGRtcaEatNg6EsYr/smEYe5gkpaVqwxweIufLFGgbJCpD4r7TgsfzCpakoUL48aoIl0P7oCubEA7Qp3453Ozf00YI=,iv:90SNhoaqmJ6Tzx91ootS6aR4S35pK/9J/ZKR6rsPSQ8=,tag:OmJwfHdQmcsAtmb66/MTzA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
