apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:xFvw+YhsxOyr3Oj1tB/1qvNbPuHQOouTb+pnEOdNRVWpOPWA26yKXcmHX+syPr6BDOB3FZR9/q2afKhblC+qCQQ7ANWjCr/Gou/KdegbHMnPgT8p8KjaQywiwgslR58rXDo/CctxUQiQ/PNBxteNTwoZ/dZ3VUBZngRToHLRDKwP6/EFQPBygsh1okXkHFgD9Djiy+Ut2DK1YAqQEEVg5lqXtJlfGf6AWvPJSigWgsyA+IdlqfAl/znXQDkdJ0+ESt8wCglypf8MygU0BEeQmojKyvYrfsWWHcHVtJx1EJj9fM2g6Pzcta6F2JlYTqGpVdDMGQOijPncdB5XWDyP9o5DHQxPNNxVIBntvfpAztwunzvh6bvXgWmH/VHPW+m7,iv:ffP4TiepYJaR9usXPafomPkVhCeCffJQ1Gr1rc6K+PM=,tag:F4NCHOYDjFBRHz99LUuGsQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:DRwqPpKPeR4dgsHbA8PkxNB2s7vVbeUoGGvYMR3M4N+xJ5F5UjdYYNA9dpdV4eC7AYW1gg0G4FWYmfSm0zNoAqlvcy9LF94UGADULIMlrqWJE+JwHlEKFBkjwFcfJL64P2A5D5eLdXW86M6evyrvr4xzEBcckAvdX6ahDc+4moN+XjlaSGlk8dQ+9GJbyEbxa8bbeUFMl5ng3H4HUN4diQVP5bLcl1OS9fkApjT9yisRz0/BguLIIrJtT+JrQFZ5llbFo7gvAb5ZYixGag==,iv:ZePDArlif6UoQpjoUdmztNc1e29b/NILUHkMwoUCCHw=,tag:4YjAvNM3ppitWZ7hGY5ohw==,type:str]
    known_hosts: ENC[AES256_GCM,data:cNFBqrkrpyepT0+pMztL0OJ06R3xZt9hdejDOg/Y4SmagrLJ6Ltr2vNCCjWxkd7k6+Ntle6GxGlfEu4Ckjpo4YChPnfkJzY+EaLTbjsby/q1RDO0bigk2AMzJdm2N94fVqyhWCkiAutFJydCgFFcnGd6zkNG1Bg6f+w3q2mYYJ6EUfJ4ooY4Nxe7ywjICHSTVlvoA7vgI4CyT41WO1kfGsEJTur8cvMZrJYU,iv:MTy8Y2ltf03P2+1bznXAUJJgJDrkWEfLDCt9xhR5l0k=,tag:MQXJnrbV2OQCHia1LJ3HWg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1nvyuzu5f6y5q6navmgp3xfjgtdyknqa9skle4kc40mdmngrvpfpszpvekr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVXhCZWpibWw0WVdlSSt2
            bE1jTWpscHBLU1VJUFZ2aFU5eFZ0QjRtTFNjCkJVUS9BS0xRYzVIbnFwT1kwVlU2
            b2JFVDNuUTd6NFRqQVlEZHZuRnVWZzgKLS0tIFd1VVFCMzk3dVB0ZnBsbkhqd0Js
            dzg4Rm5UQm9wYXNTRDl5SFVaUXBMdEUKeyz8nfTyuG2wbliM261nFsePxxurWJeR
            82FqBo/SCYauvflmfB+AXscbVCIQyKdd5zEsAYWwS2FtdILGaif3ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T00:04:36Z"
    mac: ENC[AES256_GCM,data:LSK5n4vRHvm5Et+SyuQm9Va2jPwBwJXS3LQEaed2WQ5qq+w88BH87FDEH/YXNbJUbI5Dt54hQWsb8Rscn3C5eLMX5iwgmzebU63BltAt76b+NMLbYWO9BdQlMQEQ/B69205WFuYEoMerle31KW5vrTblhxKwylHBn3wrA5cQcMk=,iv:QxivU6lDHBSR/EmHbNYlSC5W6slV38hA+oCGLRCMHx4=,tag:E+vV6i1OeiI7cDS9NJ4bTQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
