apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:v0UfZCcRsdAcUsNbDeu49aIMT9kvhxgjGYfXVPG3g+hgaAMybvmU6ls1amOCuSuyvZ0r9tkzLosu2BnOr+kJvyuQ5nzQbiiOduh3q1GA3idwUGlOHr/l2R/nt3XW2VMAFW0+OaNC5+OhgtJUwnjWbSVBQfqHKXqqYtyKg7xXZ3eO88UG6NXjRHpBeYBxarBRrPVIfd4iv5+Vcs7kE28JyqaPtFFiwxRflwuSCVALypsnQjYVq0d5cGJ1ODrCgEBkkS8gUSZI2fFfHEMxSieSuwpAJZiZAZGTrmQD58EuF6u3mAPcTzgtzb2/3mOspJpQCZ6/9wWafRwzW6/8e+F+pyhY1/JXQnBBvNGprU+F4gy8AReELcu39jtSoAgEY3Vz,iv:JidfdjOGE3fyuy2342rF5qlnk/uWfhUClgZl2YU1DzQ=,tag:3QuVjH9ksyfLWtIUDqpipw==,type:str]
    identity.pub: ENC[AES256_GCM,data:hiR29PDfzuWO2HT+EUwsmQ/T1zg+DFBmt2GQAWLCniCT2OCVdDSrsKKJpix/b+ECVpI0T+WyrhSG1cjWPM/5JRrL9lml5aKwsgtYJwZePXihQu7ZQbfjLgOv4jJIGlEzkmht1U0IG26vZK+ZnThwwMK+i5q4dP9AgdZr5zIcupzphAJXpC+dFmtf2j9OpyRhTYkI+woRTVkdZPWdcSlxa5u4Logvyz43fmhLoUTdyCLM7oI1DfI/N1x+A5SkiqwSsH+9Ue61C4MI8lMptQ==,iv:CEJIZmSPx9H5jGEGC2+c0FgyLBKCNtpSYO75p+GsKEs=,tag:xiom4t3/3qiRPHmjvWOKpQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:M22f8KgAscDK8huPgFJPAUW1WplKEBEhtMsuN3qSOlUeHW2rxyVfyNF18F4RWLOEzF0XmyqX1muPB4lcJ6P8QodrsDzb3giXjEQzgvbVQUgGimnp4ECacyAQmxUImzmIHtHwmdiwbtFgwcYaLjxH+im5EjIufv1myQNwOofW0XhVgpZ7UtU6wAr/QVEGca40B3BR3wg37vINnNgTrfShL7AzXV7gUtRMxWLC,iv:a0blG30V8n69QLOm1ADpQuYTHcq5DY9cRFd5cfkVrKY=,tag:5RVb5p8zh2yFqzhcinxBEw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1nvyuzu5f6y5q6navmgp3xfjgtdyknqa9skle4kc40mdmngrvpfpszpvekr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPazJVZEN5cFRkczVXWjRz
            TGdoaUc5NXVVeVBkQmk3Z0VNaXptTUVwbWxjCmpzQU9nNUFUZ0ZrYmZISWQxa1Zq
            UnJJUStPM3hIcS9QaitYTDk2Z0NhZ2MKLS0tIDFSVDdTL243RzBTMDFkSEZxQVkr
            b1BSY0VsM0liQnRSa2dldVNTTXUxNHMKjLajtTqadkD2uIrfXpLUj3Wblar0xzpj
            zHKOvutZ7VcoJ/aY6gMWjBMUhWUydn+Q7L19cmqhNhVVGMiU8+ipxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T23:35:46Z"
    mac: ENC[AES256_GCM,data:9zuRBhJSdS8jDOSTSFeEWn0keF63lle9Eu8JhN98binRGnp01h2htNW88qSyGftcXFJJFJ88svJ+VW/VZZa6xsNcO22pT/kF8G+FzLgX1bKzPJajRBeRriRllZvOL2o320oUEx7N1DcBDaiMtqwKd2nsL5n3QbgR8ms9a8Yo6zE=,iv:+XTRdbJXis6kU7yQ3OeVvUhAe2LT9UyUwuB3DinEovs=,tag:lieAaJoQ1p1jxFv5qQcpHg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
