apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:lJLkcbeLaadad4l/CuXSAdI95DS6QvFMM1q6ZGiyb/B6rjlri9BbqRLtRMw+hP2Cs7DmXyBV9twMqTYRmOY35o3Xecl5dqYLAkwTXz6jNfxUTGFxo9vqjSvtQQJyiehbuOKTByXzVn4uQ4oiPJg+A2HwJ404CfdlxfextEwe4reObtKQPjCV60uhRsWub3Os+pOdPjAI41F2rVrk1Om3JRs3H0joitouFBGP+jLrw2+b4CHM15uQwWwQQ7Rc0lmvayj+kQot2d4HTJVz3WItrVoTmJW7orb4i+7W+aJQ3dp38jFK9py9EEfT/oRhoT+wTHh8VUykNUNkRaLRNT8gQxiTDL8UDfuhnEcuRn/RRVUkYt4rxitOV7eDC3AVdlzK,iv:rCaSFzYfuO1sJ1+a8bl97qsLSyJX8yQrpbCZ/G3aC5Y=,tag:vYsV0g0dnm1nWcwT/hQB7A==,type:str]
    identity.pub: ENC[AES256_GCM,data:vucrRegCTM1QeR583YJvD+ct9aK00kdR5jKruB7W0hm1Zqw8PuSJ4TXyYDUuI0Y4DnplAkxzcLYbe3+LKIDss0IkcfbVk1XoUZyMO4VZk9Prwswm3kcWa1UEQRkFiw468wZvLUW9w+u8rDyqpqWoWauo8FSZAUpQ7XhGr6LDNruOiQc9mrDIiV8+eYHJxehDtANvredoc6RF14+bKNYcUXD1E3zbYghC//qg5+1Q5ejPnW5TZpyYk3ZmJKzla1WeRx28oWuYZaMdtkpDhA==,iv:/f6N8IzoNaaVp5Plgpzo1CmK6e6+jcWdFZtlwI5M32w=,tag:3NueecuB9u3t8RIFCtJ9nw==,type:str]
    known_hosts: ENC[AES256_GCM,data:5ofZNBzl8YAlNhZlTGbDCOF/4OUbIWtmoFmLAu5dhwXUYeTyDDaKApp+tNNKBgb7OdR8sib7/h45PyuYOYXpkat+Rb+JoEt+ohRcqYIh1Vh1lEZZSN2AnRwmvWLQ/T4MLWo+Q/7adD1+Ndvua/9LRvigV/+LdzQS3JLCUHIb9ifqrwc0oqrmNYvhjUJ3jdtugROyUyiLRUYt6r79vBTyS7DyUP2NbVvKfmcc,iv:ool11W1L6IyTIJc7tgDlo9sRkiiuzxqg5qgmK4eCxUM=,tag:M/zEYKJ8P205pMqQFYvAyw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1nvyuzu5f6y5q6navmgp3xfjgtdyknqa9skle4kc40mdmngrvpfpszpvekr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWmVuNm04ekt6SjFrYU10
            cE1rMERFMHBycXNqTy9TT0JLbHkrRXFlYnhBCmhJRHVRWm1INGlDLy9RWHNPUFYw
            ZnlBQzhma0t1cWRUK3dFbmJ1S2JJd1EKLS0tIHJwOWF2dFJpWkxNSzd6VGRNVGg4
            c1poSy9vRm5HRnBHM3BBQ1ZjMWlPSVkKRs6te407OvQ0ZHR8WmII6AETWid7J+MH
            /3XO7uoV+Na9D48vZtb3CYi+hTUmrIQudkvnRMlT8Boq5R3HUhYHtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T21:05:41Z"
    mac: ENC[AES256_GCM,data:LlnwVWRdru61jxaOFu/bRedp5G5/gINA0eorYtati6j499d/MGwA3kN50WEwuLutBgLl7sL9eoV7ambNNVkozpVtc7xS/cIpJwdcwhHq3CplD64Nk5q3Z4KK8zKmiqWRJybUkPmOCUhDOluKj3CzBQ96TLrLqppEgB+cy9t9vwI=,iv:0xqwi7EKKSN4Lx/UZml97E3fOHWYnIM5PWHLDOgi/a4=,tag:dtzl2hajPni/198BlGlUmA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
