apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hae60Miur2bcXsNpRwyAqyLHtbiWU0L+2Lk+gfMRQd8AFH6xSsM8t+FfdNYYrArN7sEVBC1vihjRDrcfFK2hOu6KO8Dx0WCm006TQauxwVgJ5hI1Xw3MOwdnANXcdIVJoiDFKxu0dOlCj3zM1Dz0AI32HcB/Uv8luWvcwarKe70gf6MSTKazcQyoii65cZqcbMzefjcvaCXuY/uIflESEY/64InKjJOJe7dMv5c76hHJwLU6MwOENj4auTlGwm6o9WjqLPLjts+mP7+36Uh7FZgsgMq6m9C3QjiBFTcFLUrFs35WGgtubR1PioIQh5nyR38GoCo4itCgefA33YoYMau31p3A32a7Oo1HGcQQitdG0UnGMmn9uVGyuXF3rUWa,iv:+6qohsmQjv3L49+6Twd18ubAmYuIJwm4F+XYQzGH0gw=,tag:bWbBLUHjsXooNspxdGyccA==,type:str]
    identity.pub: ENC[AES256_GCM,data:8ckpXdn18Q2uIeJfRHeHi3wQalZy3SJEo+Lj9AFxjYbjDm3YcUQV+lM6w7BfS6KImi5y8MtIlgwcoApavgwZnYU6yh1euqgOKZjoApWzsRJFNaE/mfMy7ATOSNKiK759KU9eVdlQMndmcK9Y0pDBwjjsqBL7DhiN42M2gAT7msJgN2Xw2+Ca/TQpc9tEkIVM+a9SouI8+xxzjgxLmU7IKq1JJMWYPfDw3veInqSKR865Neo+sEMvWBqAN5BggQoYmf+/heWCPCezdWniEg==,iv:0cW3M8aWgPTTd1a3xB0UgWIafiB+ujSEqHYI4nzwS7g=,tag:LMIsw/MvH5PL0sR+0SNywA==,type:str]
    known_hosts: ENC[AES256_GCM,data:eX7aeYcS5/Wyy7udcIPQsxpM/sFuHQUd21s1wITnsW73krGmWdc5iBH2UuJ2WFmE6Ki/M7P+sTpGDEHQWtjNBcz/Exg745mavdHHimw2fQg2GmEDwlrBy/VwONMsQxUxohArUu+7Xv3T89cR2W0RYV8FUthgaqTc+yXROEn7uT46AeRYJNEKXzMqSOwn8kkmDo9mjpJsgpv2U7w7eM0N0kdiPRtE2jz6op24,iv:yll43051lE4h2ww1tLh1jf3a/DVkiP7iB0sFkLpN1A4=,tag:aWZxMpZTcbUxERvABC5gEQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1nvyuzu5f6y5q6navmgp3xfjgtdyknqa9skle4kc40mdmngrvpfpszpvekr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dzhmeVpCZy8yQW55Qzdj
            THQraFhSelNLbTZFdnN4cGl6SzFJSjZjQzAwCkFuSEYwMjE4Ynlob3BEeFpWVUxG
            M2FkV1V5T2sxbzZhQWZQMmJjUGJ6aDgKLS0tIGtuZGlMUlgva04xMkIvclVwM0JL
            TFZPYms0N3cxa2U5YW5kY3NKakRiYW8K2iU0/wmsdtzTm0wqcl2/YPvE6lwNDrv/
            PT8pF8gJN2VMfXzJNVxZCLE1xJHVGr2DX7RRoCFDfmmbFzi3qqVFuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T02:32:01Z"
    mac: ENC[AES256_GCM,data:izwX0hbIXKFy9YSSXVLhusyzHllAMS6b0/zApLvMol7VFp+p2rAyigvaueEI4P1jeCUS7WlDOz4EgujgxWOBL9FudSJwOoVDERq39Idr33wvsREjVlk7U/WR0ljSuUO5mfDCf4igdZ27ZaD4BCmdJD9XMU4rStL8T7uFzEv0eWU=,iv:Tdbkouirgx7aVWhJdlsdDQy3sOASEcTbPrYZ7Qzv/1U=,tag:kEh5+2JD0ZWjreQmE7SDdg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
