apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:yw0p445Ab1VL/oGJgMc6Ben6KxfQWKf2DheC+9TRWT/ygi5I0LOG1cSNAU6ir3wsEx8QcY+a967qBoeQGJtMIgL+dcNJYv/nVPgcv/ZdhGGW9YsUERM0GhKneCt5XUV2HzyVLz32KIKwRW/XYcHOjVsS2wLbN5r7mAyTYtHfrvilc6eOfZolBaqf+OsJ5/YfNvOAqLyecqTS1/clgDELSXoJDamkxhf5l/Wc/Q42R6f3Bf6vA1COfyHiVWP8z3tC2LoWDeSzrny3bH3Cc5zMBRiVGzjsPhAxL4AyHy9DsWRptBe2/EMZ5bZojmHLB6z4Xuf059V7UWPdc5FS2+6HD8eqt1olxJDJ/r3ikD2R0IpW3qRBrCunnFwx/IYOOfqT,iv:CJi3QxJnaoSHBf0jSbhkn32MGwFUYrjGl3ccBp/wD4o=,tag:125fp5QpaLKridlLLcmTSg==,type:str]
    identity.pub: ENC[AES256_GCM,data:X67eo9H+AToiJUwSH7CE3Aqi7pzEhBwL7DIxbWbSIFm2lndnPaRFR/dqO+5VFsnnb/d6cVGVL1Uv6dyOze4UBE1Ld322G+VUEIPp3kNlWT4H+G2KRrM2HIgR6pza543NHf9Pgi6QSPcBI18S5Sw364mYDKuTUrSlrzKcY/GB8IomRbg7VLVIPiE+HE7Ynjfg6xXBcuWo6sRFYNz3rtm7ELbAmFqFRd4RoVPcyaJpsjWT8njTAOQuOrxvRAVMMjHi4rtqIvLSaO20x2/JAw==,iv:3zLo43IHAGvoMwraWWgq1Qa3x7o9tHGBJMOLOLtvuNk=,tag:FoYD5rCbGWKWfgPBdX76Fg==,type:str]
    known_hosts: ENC[AES256_GCM,data:Z4XmukJQqUUsyv/AIZ92pU+w+402OzdQ+u3RZZkmdpKyuX9WHZAnTVSpwh2iUB+oao/AD0KAXno7H4RIOP9hkYAzKTkfy4tSRRZrSlaJv/X+DWfw1RC3e2Mr+gh1NMH7vev0SDYlfdHT9JxDgNaCvjXeekkrRtakTFVvE4lfRJyqQE3UaN/3UW+5pxf7E1LJfTlco8waqRex/T9bJnGf5S+QDREQTMczcZCg,iv:4lW73Uqc06dlr2Dh+5z84PhsJNWZEEwmicelfks1lAY=,tag:JR80qR3zhZMxFVrfZAGFYg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1nvyuzu5f6y5q6navmgp3xfjgtdyknqa9skle4kc40mdmngrvpfpszpvekr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZWR3WU8rRUViaXRuc3FE
            TlVMeDFDSTZDQldCd05sbjEzUkl4SStYekF3CjhwYXVsVkdmWVkxUlFlVXNrMHJu
            WjFFOFRUdVJiRVdvWElVb3BEU3B3Wk0KLS0tIHBOYXVTVm9JN0ttaXJ5eDBTY3Vy
            ZXNBVkg2dGdOK2JTUGppQzZXYVU4ZFEKggHP+oKu8uZC4A2sSHpJxXVG17dK5nYk
            0X6eAEL3OzlvMglt1CwryOUP5QPBzRrpI5mDNYKJiiOlsALM8KGYUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T21:05:17Z"
    mac: ENC[AES256_GCM,data:LO5/Zd4WTe7FU5Xa/xUoEjHqX1OdmbMedICs370jKoFKq+Lt9GQ4//15KNh/6SnyIfLeJXH3BY8UDhTnAkmgQ9h12UajBo7p9j4or8IfChqBHH1gYMnwp7ouu5tsnz8uJ4Ny6veW0tFgOX8GS2S6WE3uUrUPuViKZ0YyNgaweKc=,iv:xROJWZ0v39CuTxPt7227sAgXf1+/MUYwAbvIK8tkwAY=,tag:yqxSqbjGa/QxZmjKhLj9Ow==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
