apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bazarr/ks.yaml
  - calibre/ks.yaml
  - calibre-web/ks.yaml
  - lidarr/ks.yaml
  - maintainerr/ks.yaml
  - prowlarr/ks.yaml
  - recyclarr/ks.yaml
  - seerr/ks.yaml
  - sonarr/ks.yaml
  - radarr/ks.yaml
  - whisparr/ks.yaml
